# backend/Dockerfile.dev
FROM ruby:3.4.6

# Installa le dipendenze di sistema necessarie per MySQL e Rails
RUN apt-get update -qq && apt-get install -y build-essential default-libmysqlclient-dev git

# Cartella di lavoro nel container
WORKDIR /rails

# Copia solo i file delle gemme per sfruttare la cache di Docker
COPY Gemfile Gemfile.lock ./

# Installa le gemme
RUN bundle install

# Espone la porta 3000
EXPOSE 3000

# Comando di default (avvia il server bindato su tutti gli IP locali)
CMD ["rails", "server", "-b", "0.0.0.0"]