FROM ruby:3.4.6

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev git libvips

WORKDIR /rails

COPY Gemfile Gemfile.lock ./

RUN bundle install

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]